name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Set API Key
      run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
    - name: Run tests
      run: swift test --enable-code-coverage
    - name: Convert coverage to lcov
      run: xcrun llvm-cov export -format="lcov" .build/debug/LandTransportKitTests.xctest/Contents/MacOS/LandTransportKitTests  -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: info.lcov
        token: ${{ secrets.CODECOV_TOKEN }}
