name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Set API Key
      run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
    - name: Run tests
      run: swift test --enable-code-coverage
    - name: Convert coverage to lcov
      run: |
        brew install llvm
        mkdir -p .build/coverage
        export BINARY=$(swift test --show-bin-path)/LandTransportKitTests.xctest/Contents/MacOS/LandTransportKitTests
        xcrun llvm-cov export \
          -format=lcov \
          "$BINARY" \
          -instr-profile .build/debug/codecov/default.profdata \
            > .build/coverage/coverage.lcov

    - name: Upload to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: .build/coverage/coverage.lcov
        token: ${{ secrets.CODECOV_TOKEN }}
